[package]
name = "app"
version = "0.1.0"
description = "Cross-platform SSH connection manager for cloud and private infrastructure"
authors = ["Asim Ahmed Siddiqui"]
license = "MIT"
repository = "https://github.com/AsimAhmedSiddiquii/CloudTerm"
edition = "2024"
rust-version = "1.90"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.7.1", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.12.1", features = [] }
anyhow = "1.0.104"
tokio = { version = "1.53.2", features = ["full"] }
russh = { version = "0.64.1", default-features = false, features = ["ring", "flate2", "rsa"] }
tauri-plugin-dialog = "2.8.1"
tauri-plugin-store = "2.5.0"
tauri-plugin-process = "2.4.0"
tauri-plugin-updater = "=2.12.0"
aes-gcm = "0.11.1"
argon2 = "0.6.0"
rand = "0.10.3"
russh-sftp = "3.0.1"
aws-config = "1.8.13"
aws-sdk-ec2 = "1.208.0"
aws-types = "1.3.11"
